from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
       path('analyatics/', views.analyatics, name='analyatics'),
    path('analyatics/<slug>', views.facebook_page, name='facebook_page'),
    path('fblogin/', views.fblogin, name='fblogin'),
      path('signin/', views.signin, name='signin'),
        path('schdule/', views.signup, name='signup'),
          path('strategy/', views.strategy, name='strategy'),
          path('showstrategy/', views.showstrategy, name='showstrategy'),
          path('updatestrategy/<int:id>/', views.updatestrategy, name='updatestrategy'),
             path('deletestrategy/<int:id>/', views.deletestrategy, name='deletestrategy'),
           path('logo/', views.logo, name='logo'),
            path('showlogo/', views.showlogo, name='showlogo'),
            path('updatelogo/<int:id>/', views.updatelogo, name='updatelogo'),
            path('deletelogo/<int:id>/', views.deletelogo, name='deletelogo'),
           path('competitors/', views.competitors, name='competitors'),
                path('billing/', views.billing, name='billing'),
                 path('showbill/', views.showbill, name='showbill'),
                  path('updatebill/<int:id>/', views.updatebill, name='updatebill'),
                   path('deletebill/<int:id>/', views.deletebill, name='deletebill'),
                  path('socialmedia/', views.socialmedia, name='socialmedia'),
                          path('calendar/', views.CalendarView.as_view(), name='calendar'),
                         path('event/new/', views.event, name='event_new'),
                         	path('event/edit/(?P<event_id>\d+)/', views.event, name='event_edit'),
                                  path('Approvecontent/', views.ApproveContent, name='Approvecontent'),
                                    path('showcontent/', views.showcontent, name='showcontent'),
                                      path('updatecontent/<int:id>/', views.updatecontent, name='updatecontent'),
                                        path('deletecontent/<int:id>/', views.deletecontent, name='deletecontent'),
                                    path('calenderview/', views.calenderview, name='calenderview'),
                                        path('contactus/', views.contactus, name='contactus'),
                                         path('starttoday/', views.starttoday, name='starttoday'),
                                            path('showstarttoday/', views.showstarttoday, name='showstarttoday'),
                                              path('updateschdule/<int:id>/', views.updateschdule, name='updateschdule'),
                                                path('schduledelete/<int:id>/', views.schduledelete, name='schduledelete'),
                                                 path('logout/', views.ulogout, name='logout'),
                                                  path('user/', views.userlist, name='user'),
                                                      path('userdelte/<int:id>/',views.usertdelete, name='userdelte'),
                                                         path('UpdateUser/<int:id>/',views.UpdateUser, name='UpdateUser'),
                                                          path('api/fb/page/chart/<int:id>/<str:data>/<int:days>/',
                                                          views.fb_page_data, name='fb_page_data'),
                                                          path('api/fb/page/data/<int:id>/<int:days>/',
                                                             views.fb_page_data1, name='fb_page_data1'),


]