# Generated by Django 4.0 on 2022-01-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_extend_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='addlogo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.FileField(null=True, upload_to='logo/')),
            ],
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.FileField(null=True, upload_to='videos/')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SchduleDemo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('DealershipName', models.CharField(max_length=100)),
                ('Emailaddress', models.CharField(max_length=100)),
                ('PhoneNo', models.CharField(max_length=100)),
                ('help', models.CharField(max_length=100)),
                ('Question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='startegy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment', models.FileField(null=True, upload_to='attachment/')),
                ('note', models.CharField(max_length=100)),
            ],
        ),
    ]
