# Generated by Django 4.0 on 2022-02-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_addlogo_content_schduledemo_startegy'),
    ]

    operations = [
        migrations.CreateModel(
            name='billingtable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice', models.FileField(null=True, upload_to='invoice/')),
            ],
        ),
    ]
