# Generated by Django 4.0 on 2022-02-10 10:39

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_event_title_startegy1'),
    ]

    operations = [
        migrations.CreateModel(
            name='fb_user_pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(blank=True, max_length=50)),
                ('page_name', models.CharField(blank=True, max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='page_name')),
                ('page_access_token', models.CharField(blank=True, max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='fb_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('user_name', models.CharField(blank=True, max_length=50)),
                ('user_access_token', models.CharField(blank=True, max_length=2000)),
                ('pages', models.ManyToManyField(to='mainapp.fb_user_pages')),
            ],
        ),
    ]
